### ISSUE TITLE
Problems to read Winboard PGN format in crazyhouse variant.

### ISSUE THREAD

**Issue by CPagador** [ml-research/liground#121]
Nice tool for analysis. I already tested it with crazyhouse variant and looks great. Only detail is that has problems reading WB's pgn format, only reads some moves, meanwhile it has no problems with cutechess' pgn format.

**Winboard:**

```
[Event "Computer Chess Game"]
[Site "DESKTOP"]
[Date "2021.02.22"]
[Round "1"]
[White "Tscp crazyhouse 1.1"]
[Black "Pulsar 2009-9b"]
[Result "1-0"]
[TimeControl "600+2"]
[Variant "crazyhouse"]
[Annotator "1. +0.22 1... -0.38"]

1. e4 {+0.22/8} Nc6 {-0.38/7 25} 2. Nf3 {+0.33/7 21} d5 {-0.17/7 31} 3.
exd5 {+0.47/7 20} Qxd5 {-0.12/7 27} 4. Nc3 {+0.48/6 20} Qe6+ {+0.04/6 28}
5. Be2 {+0.60/6 19} Qg4 {-0.53/6 27} 6. P@d5 {+0.72/6 18} Nb4 {-0.19/6 19}
7. a3 {+0.84/6 18} P@d4 {-1.29/6 24} 8. axb4 {+1.04/7 17} dxc3 {-2.06/6 23}
9. dxc3 {+1.04/6 17} Qxg2 {-2.05/5 17} 10. Rg1 {+1.29/5 16} Qh3
{-3.45/5 20} 11. P@e6 {+1.93/5 16} N@g2+ {-2.21/5 15} 12. Rxg2 {+3.14/7 15}
Qxg2 {-3.38/6 15} 13. exf7+ {+3.14/5 15} Kd8 {-4.25/6 19} 14. fxg8=Q
{+3.84/5 15} Rxg8 {-4.87/5 19} 15. P@e6 {+10.35/5 14} P@e4 {-4.09/5 16} 16.
N@c6+ {+6.88/5 14} bxc6 {-2.23/5 12} 17. dxc6+ {+99.87/5 8} P@d2+
{-4.53/5 15} 18. Qxd2+ {+99.89/5 2.0} N@d3+ {-19.32/5 13} 19. Qxd3+
{+99.91/5 0.4} R@d6 {-149.96/6 15} 20. N@f7+ {+99.93/4 0.2} Ke8
{-149.97/5 11} 21. P@d7+ {+99.95/3 0.1} Bxd7 {-149.98/5 13} 22. cxd7+
{+99.97/2 0.1} Rxd7 {-149.99/5 10} 23. Qxd7# {+99.99/1 0.1}
{Xboard adjudication: Checkmate} 1-0
```

**Cutechess:**

```
[Event "My Tournament"]
[Site "?"]
[Date "2021.02.18"]
[Round "1"]
[White "Fairy Stockfish 10x10 11.2"]
[Black "TJchess 1.3"]
[Result "1-0"]
[GameDuration "00:01:21"]
[GameEndTime "2021-02-18T03:57:20.773 Hora est. Pacífico, Sudamérica"]
[GameStartTime "2021-02-18T03:55:59.704 Hora est. Pacífico, Sudamérica"]
[PlyCount "45"]
[TimeControl "60+0.5"]
[Variant "crazyhouse"]

1. e4 {+1.33/16 2.5s} Nc6 {-0.03/11 1.0s} 2. d4 {+2.23/13 0.42s}
d5 {+0.01/11 1.0s} 3. e5 {+0.83/15 1.9s} Bf5 {-0.08/10 0.80s}
4. Bb5 {+1.50/16 1.8s} a6 {-0.11/10 1.2s} 5. Bxc6+ {+2.73/16 0.66s}
bxc6 {-0.20/10 0.65s} 6. Nc3 {+3.20/15 1.4s} e6 {-0.22/9 1.1s}
7. Nf3 {+3.00/17 7.5s} B@h5 {-0.24/9 1.2s} 8. O-O {+2.20/16 3.2s}
Bxf3 {+0.13/10 1.3s} 9. Qxf3 {+5.92/14 0.81s} Bxc2 {+0.59/9 2.1s}
10. Bg5 {+9.18/16 3.2s} Qxg5 {+1.02/9 3.1s} 11. B@d7+ {+10.56/16 1.2s}
Ke7 {+0.56/9 2.3s} 12. Bxc6 {+20.95/14 0.90s} B@g4 {-0.13/8 3.7s}
13. P@d6+ {+21.88/17 5.2s} cxd6 {-1.06/9 3.6s} 14. exd6+ {+25.22/15 0.51s}
Kxd6 {-0.43/9 5.5s} 15. Qxf7 {+28.33/14 1.0s} Kxc6 {-1.12/8 1.4s}
16. P@b7 {+39.86/15 1.4s} N@f3+ {-3.35/8 3.0s} 17. Kh1 {+50.34/13 1.3s}
Rb8 {-10.25/8 4.3s} 18. P@c7 {+56.52/12 1.2s} P@e7 {-M10/7 2.1s}
19. cxb8=Q {+M9/23 0.76s} B@d6 {-M8/7 2.8s} 20. Qc8+ {+M7/25 0.78s}
Kb6 {-M6/6 0.037s} 21. b8=Q+ {+M5/42 0.82s} Bxb8 {-M4/5 0.18s}
22. R@b7+ {+M3/245 0.12s} Ka5 {-M2/4 0.002s}
23. b4# {+M1/245 0.063s, White mates} 1-0
```

Not sure why, they look the same to me.

**Comment by QueensGambit** [comment]
Hello @CPagador ,
thank you for raising this issue.
I tried to replicate the problem, but for me the pgn seems to have loaded correctly.
The final FEN position for me is:
`r3kbr1/p1pQpNpp/4P3/8/1P2p3/2P2N2/1PP1BPqP/R1B1K3[RBNNPpp] b Q - 0 23`
which is the same as when I load the pgn on lichess.org.
`r3kbr1/p1pQpNpp/4P3/8/1P2p3/2P2N2/1PP1BPqP/R1B1K3/RBPNNpp b Q - 0 23`

You did use LiGround 0.1.0, right?
What is your final FEN position after loading the first pgn?

I also generated a game in XBoard, exported the pgn and later imported it to LiGround.
This seems to have worked, too.

My assumption is that Winboard may add specific line-endings on Windows which causes the problem.
Internally, LiGround uses **ffish.readGamePGN(pgnString)** from the [ffish.js](https://www.npmjs.com/package/ffish) library to read pgn strings.

**Comment by CPagador** [comment]
> You did use LiGround 0.1.0, right?

Yes.

That is the first game of a pgn containing 132 zh games. 

[CrazyhouseDiv3.zip](https://github.com/ml-research/liground/files/6087316/CrazyhouseDiv3.zip)

This is a screenshot of how LiGround reads the games:

https://i.postimg.cc/qMsyc0RB/liground.jpg

**Comment by QueensGambit** [comment]
Thank you for the additional information.
I am able to replicate the problem now.
It seems that the problem only occurs when multiple games are loaded from a single pgn file.

We'll have a look at that.

**Comment by ptrmdr** [comment]
I just had a look at this problem and I think it is about the line endings. I think ffish.js can't handle CRLF. It only works for LF so for now we could just replace CRLF with LF before parsing the string.
