### ISSUE TITLE
Support 3check pasting of other FEN variants

### ISSUE THREAD

**Issue by magehrke** [ml-research/liground#185]
- `LiGround` currently only supporst `3check` FENs like this: 

      rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 3+3 0 1

- It would be nice, if `LiGround` would also support the same position, but in a slightly different FEN that is widely used (e.g. by `lichess.org`). In this notation the same position would be 

      rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 +0+0

**Comment by ianfab** [comment]
The FEN parsing in the core engine actually already supports that, so I assume it is only rejected in the ffishjs FEN validation.

**Comment by ianfab** [comment]
FEN validation will support it in the next ffishjs version: https://github.com/ianfab/Fairy-Stockfish/pull/398
