### ISSUE TITLE
korean chess??

### ISSUE THREAD

**Issue by cjssh1002** [ml-research/liground#19]
Can I play fairy stockfish korean chess?

**Comment by BododB** [comment]
Hi,
at the moment it is not possible however we are currently working on implementing different variants including Janggi and Xiangqi.

**Comment by cjssh1002** [comment]
I would like to help you in your development of how to implement Korean chess and Korean chess rules. Do you have a messenger or discord that can be more active with you?

**Comment by BododB** [comment]
Hi,
thanks a lot for your offer.
Unfortunately since this is a student project we can't accept your help. But I can assure you that at least Janggi and Xianngqi will be implemented shortly.
