### ISSUE TITLE
Game Result not displayed correctly for variants

### ISSUE THREAD

**Issue by maxalexger** [ml-research/liground#210]
At the end of the game, LiGround is expected to show `1-0`, `0-1` or `1/2 -1/2` to the left of the engine logo, determining if white won, black won or the game is drawn, respectively. However, this only works correctly, if the game ended due to a `checkmate`. 

For many variants, like `kingofthehill`, there are other ways to win the game. Currently `LiGround` uses a `ffish` function to check, if there are any legal moves left, but not how the game result looks like. The rules for chess are hard coded in `LiGround` and so the GUI assumes that it's a draw, if no king is in check. 

We would need to use a function `check_result` that encodes all the rules of the variants and returns the correct end game result.

**Comment by QueensGambit** [comment]
Closed by #211.
