### ISSUE TITLE
mpm ERR! for dependency tree issue

### ISSUE THREAD

**Issue by nicolast0604** [ml-research/liground#227]
nioclast0604@nioclast0604-VirtualBox:~/liground$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: liground@0.2.0
npm ERR! Found: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   vue@"^2.5.16" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.0.4" from vue-float-menu@1.9.0
npm ERR! node_modules/vue-float-menu
npm ERR!   vue-float-menu@"^1.9.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/nioclast0604/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nioclast0604/.npm/_logs/2021-09-17T02_16_51_957Z-debug.log

**Comment by QueensGambit** [comment]
Hello @nicolast0604 ,

can you provide information if you use Linux or Mac and which npm you are using?
Have you tried updating your npm version? 
For Ubuntu: 
```shell
sudo npm update npm -g
```

Can you successfully install other npm projects, such as a hello-world project?
* https://www.npmjs.com/package/hello-world-npm

**Comment by nicolast0604** [comment]
Hi QueensGambit
Now it works and there must be something wrong on my side.
Sorry for the inconvenience and thanks a lot for your help.



nioclast0604@nioclast0604-VirtualBox:~/liground$ npm install

> liground@0.2.0 postinstall
> node scripts/postinstall.js

Downloading stockfish binary from https://github.com/niklasf/Stockfish/releases/download/fishnet-20200613/stockfish-x86_64...
Downloading multi-variant-stockfish binary from https://github.com/ddugovic/Stockfish/releases/download/variant_sf_10/stockfish-x86_64...
Downloading fairy-stockfish binary from https://github.com/ianfab/Fairy-Stockfish/releases/download/fairy_sf_13/fairy-stockfish-largeboard_x86-64...
Download of multi-variant-stockfish completed!
Download of stockfish completed!
Download of fairy-stockfish completed!

changed 1 package, and audited 1146 packages in 15s

124 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


nioclast0604@nioclast0604-VirtualBox:~/liground$ sudo npm update npm -g
[sudo] password for nioclast0604: 
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.15
added 2 packages from 2 contributors and updated 3 packages in 86.402s


nioclast0604@nioclast0604-VirtualBox:~$ npm install -g nimstall

added 1 package, and audited 2 packages in 14s

found 0 vulnerabilities
nioclast0604@nioclast0604-VirtualBox:~$ nimstall -g hello-world-npm

added 1 package, and audited 2 packages in 5s


found 0 vulnerabilities

**Comment by QueensGambit** [comment]
Great, I'm glad to hear that!
