### ISSUE TITLE
Board Design and Variants - US_6

### ISSUE THREAD

**Issue by BododB** [ml-research/liground#23]
Description:
As a user I want to be choose between more variants to analyse them.

Acceptance Criteria:
Shogi, Xiangqi, Janggi, and Makruk are supported. These variants will be correctly displayed in the drop down menu and enable the user to switch between all available variants. If needed the chess board, engine and design will be adjusted to the chosen variant.

**Comment by Zerthox** [comment]
Closing this, as #57 was merged.
