### ISSUE TITLE
[Question] Board rotation possible?

### ISSUE THREAD

**Issue by moostoet** [ml-research/liground#245]
I apologize in advance if this is not the right place to ask this question as I do not seem to see any other place to do so reliably -- is the option to rotate the board so that e.g. black pieces are on the bottom added? I didn't seem to see it anywhere in the GUI, so I was curious.

Thanks in advance, and apologies if this wasn't the right place to ask! 🙏

**Comment by QueensGambit** [comment]
Yes, there is a rotate board button next to the game navigation arrows.
![image](https://user-images.githubusercontent.com/15967624/160592135-18754ae3-03e9-4474-b21e-8bd67869c241.png)
However, it looks like the rotate button is broken in version 0.4.0 for some reason unfortunately.

**Comment by QueensGambit** [comment]
Fixed in https://github.com/ml-research/liground/commit/b69124c89c21bd1f3388622c5319dcdef9927b7d.
Thanks to @goekaykaraahmetli .
