### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by Sportsmen** [ml-research/liground#253]
1. What should we put in the NNUE path to make it work?

<img width="719" alt="image" src="https://user-images.githubusercontent.com/24534158/192111624-4f165821-bc17-4f63-9fcb-0a83b09e6f91.png">

2. If we have multiple NNUE's for each variant, do we need to set up individual Fairy Max for each variant? SF Fairy Max ZH, SF Fairy Max KOTH, etc?

Thanks

**Comment by QueensGambit** [comment]
1. According to the [Fairy-Stockfish readme](https://github.com/ianfab/Fairy-Stockfish) EvalFile should contain the following:

> EvalFile

> The name of the file of the NNUE evaluation parameters. Depending on the GUI the filename might have to include the full path to the folder/directory that contains the file. Other locations, such as the directory that contains the binary and the working directory, are also searched.

2. I think you need to setup an individual engine for each NNUE network, but maybe there is a more elegant way to set this up? @gbtami, @ianfab

**Comment by gbtami** [comment]
You can use one engine and change EvalFile UCI option when you change UCI_Variant.
at least this is how we use nnue files in https://github.com/gbtami/fairyfishnet/blob/master/fairyfishnet.py#L594

Btw, @Sportsmen it is Fairy-Stockfish, not Fairy-Max who supports nnue files :)

**Comment by ianfab** [comment]
See https://github.com/ianfab/Fairy-Stockfish/wiki/Settings#evalfile
