### ISSUE TITLE
Crazyhouse dropping pieces issue

### ISSUE THREAD

**Issue by Sportsmen** [ml-research/liground#254]
When I am analyzing a crazy house game and need to grab a piece and drop it on the board, it does not allow it. I have the click the piece, sometimes right click, keep trying to drop it and after 5-10 tries it drops the piece on the square.

**Comment by neito5** [comment]
Same issue on Windows 10. 
What always works for me: Double click on the piece you want to drop, hold the mouse button down after the 2nd click and then from there just drag the piece onto the board.

**Comment by blablakali** [comment]
Same for me, but also with Shogi.

**Comment by Sportsmen** [comment]
Its a shame it's a good piece of software but they need to get rid of a few kinks. Sadly I do not think it's being developed anymore.

**Comment by Feliks-WR** [comment]
so late...
________________________________
منجانب: Johannes Czech ***@***.***>
‏‏بھیجا گیا: 14 مئی, 2024 19:27
بطرف: ml-research/liground ***@***.***>
Cc: Feliks-WR ***@***.***>; Comment ***@***.***>
‏‏موضوع: Re: [ml-research/liground] Crazyhouse dropping pieces issue (Issue #254)


Closed #254<https://github.com/ml-research/liground/issues/254> as completed via #274<https://github.com/ml-research/liground/pull/274>.
