### ISSUE TITLE
Compatibility issue with Pikafish Xiangqi Engine

### ISSUE THREAD

**Issue by ztqwerty** [ml-research/liground#261]
Recently there comes a very high performance (probably the best so far) Xiangqi engine Pikafish: https://github.com/official-pikafish/Pikafish. 

However so far it doesn't seem to be well supported by LiGround (seems there is some compatibility issue). Although I was able to load Fairy Stockfish Xiangqi variant successfully. 

Any plan to add Pikafish to the compatibility list?

**Comment by ztqwerty** [comment]
Just found a solution: https://github.com/mtaktikos/Pikafish/releases/tag/pikafish-liground-230216

**Comment by QueensGambit** [comment]
Alright, thanks for letting us know.
