### ISSUE TITLE
A problem i met when i using it on VMware (Virtual machine)Ubuntu

### ISSUE THREAD

**Issue by 38alysia** [ml-research/liground#279]
![image](https://github.com/user-attachments/assets/092acd0a-9b2a-48ea-8d85-75bebc85f477)
Is it still not allowed to use on this platform?

**Comment by 38alysia** [comment]
i run the .AppImage successfully by adding -- no - sandbox followed by the original command

**Comment by QueensGambit** [comment]
Thank you for letting us know. :+1:
