### ISSUE TITLE
Stockfish download as postinstall action

### ISSUE THREAD

**Issue by Zerthox** [ml-research/liground#78]
We could use npm's `postinstall` script option (see [npm scripts documentation](https://docs.npmjs.com/cli/v7/using-npm/scripts)) to automatically download a Stockfish binary after `npm install` is run.

**Comment by QueensGambit** [comment]
If we include this install step, we may want to to download the latest release from
* https://github.com/niklasf/Stockfish

instead.

The releases from https://github.com/niklasf/Stockfish are published more frequently and is the same binary as on lichess.org.
